### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Dazmed707** [Bhaviktutorials/BloodyRat#3]
I have a error in build apk
![image](https://user-images.githubusercontent.com/35184132/128785366-d69c3ac0-a932-4b19-b2f3-62bf1cd30b75.png)

**Comment by Dazmed707** [comment]
follow the same error
I also changed the account name and the old name still comes out, and I have already reinstalled the program.
also change the name of the folder (Bloodyrat-main to Bloodyrat)

![image](https://user-images.githubusercontent.com/35184132/129372840-adeadf8f-e5e2-4010-aa73-37e4ca128309.png)

**Comment by Bhaviktutorials** [comment]
you have put space in between hack tool folder name remove that space and run it again then your error will be solved

**Comment by Dazmed707** [comment]
Thanks, rat full compile.
